spring.datasource.url=jdbc:h2:mem:fitzonedb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.h2.console.enabled=true
spring.jpa.hibernate.ddl-auto=update

jwt.secret=94a08da1fecbb6e8b46990538c7b50b291db7b587a829e74d39e9e1c2557997c4587c68a4c8c7608a0d24e13
jwt.expiry-ms=86400000
